disableStartupPopups: true
notARepository: "skip"
promptToReturnFromSubprocess: false
git:
    pagers:
        - externalDiffCommand: difft --color=always
customCommands:
    - key: C
      description: "AI commit"
      command: gitscribe commit
      context: files
      output: terminal
